public class OppProQuanPrice_TriggerClass{

public static boolean isFromTrigger=false;
public static boolean isFromTriggerCloneOppBasedonCriteria=false;
public static boolean isFromTriggerCloneOppBasedonCriteria_renewal =false;
public static boolean isFromQuoteLineItemTrigger =false;

///Variable for OppProQuanPrice setting tru in CallOpplineitem trigger ion Opportunity
public static boolean isOppTypeChanged = false;
public static boolean isLogicDone = false;
}