/**
 * This class contains unit tests for apex class MarketoTutorialController.
 */
@isTest
private class TestMarketoTutorialController {

    static testMethod void myUnitTest() {
/*
        Tutorial__kav MarketoTutorialControllerObject = new Tutorial__kav();
        MarketoTutorialControllerObject = [select Id, knowledgeArticleId,Title,UrlName, IsVisibleInPkb , Tutorial_Article_Text__c,(select DataCategoryGroupName, DataCategoryName From DataCategorySelections) from Tutorial__kav where publishstatus='Online' and Language='en_US' limit 1];
        PageReference pageRef = Page.MarketoTutorial;     
        pageRef.getParameters().put('Id', MarketoTutorialControllerObject.knowledgeArticleId);
        Test.setCurrentPage(pageRef);
        MarketoTutorialController controller1 = new MarketoTutorialController(new ApexPages.StandardController(MarketoTutorialControllerObject));  
        pageRef.getParameters().put('Id', MarketoTutorialControllerObject.knowledgeArticleId);
*/
    }
}